version: "3.1"
services:
  mvn:
    image: maven:3.9
    entrypoint: mvn
    working_dir: /app
    volumes:
      - maven-repo:/root/.m2/repository
      - ./backend:/app

  app:
    image: maven:3.9
    working_dir: /app
    volumes:
      - maven-repo:/root/.m2/repository
      - ./backend:/app
    ports:
      - "8080:8080"
    command: ["mvn", "spring-boot:run"]

  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo-ecommerce
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  maven-repo:
  pg-data:
